[package]
name = "vorbis_sys"
description = "Low-level FFI bindings for libvorbis, vorbisfile, and libvorbisenc"
authors = ["Alejandro González <AlexTMjugador@users.noreply.github.com>"]
license = "BSD-3-Clause"
version = "0.0.1"
edition = "2021"
links = "vorbis"
rust-version = "1.60.0"

[dependencies]
ogg_sys = { version = "0.0.1", path = "../ogg_sys" }

[build-dependencies]
cc = "1.0.73"
git2 = { version = "0.15.0", default-features = false }
bindgen = { version = "0.61.0", optional = true }

[features]
# Requires Clang and slows down the build, but guarantees that the bindings are up to date.
# It usually is better to run the generate-bindings.sh script instead
build-time-bindgen = ["bindgen"]
